### ISSUE TITLE
Tracking Users and Submissions

### ISSUE THREAD

**Issue by snohio** [OrlandoDevs/ignite-the-holidays#3]
# Speaker Process Completion Tracker

### Talk Title: Welcome to Ignite the Holidays

Scheduled Time : 7:30

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: AO4SD - Accelerate Orlando for Software Developers

Scheduled Time : 7:35

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: Software Quilts

Scheduled Time : 7:40

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: How to take good notes

Scheduled Time : 7:45

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: Frequencies: an interactive sound therapy app

Scheduled Time : 7:50

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: Unit testing the Linux Kernel

Scheduled Time : 8:15

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: Surviving My First Year as a Full-time Software Engineer

Scheduled Time :  8:20

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### When crisis sets in: How should we manage critical website changes?

Scheduled Time : 8:25

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: Why Go?
Scheduled Time : 8:30

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
- [ ] Pronunciation

### Talk Title: Boundaries, Game Theory, and James Bond Villians

Scheduled Time : 8:35

- [ ] Confirmed Coming
- [ ] Registered for the Event
- [ ] Uploaded Slide Images
- [ ] Tested Slide Presentation
